mutation CreateTrack(
  $name: String!,
  $artistName: String!,
  $albumName: String!,
  $imageUrl: String,
  $isCommunity: Boolean!
) @auth(level: USER) {
  track_insert(data: {
    name: $name,
    artistName: $artistName,
    albumName: $albumName,
    imageUrl: $imageUrl,
    isCommunity: $isCommunity,
    owner: { uid_expr: "auth.uid" }
  })
}

mutation UpsertUser(
  $displayName: String,
  $email: String
) @auth(level: USER) {
  user_upsert(data: {
    uid_expr: "auth.uid",
    displayName: $displayName,
    email: $email
  })
}

mutation CreatePlaylist(
  $name: String!,
  $description: String
) @auth(level: USER) {
  playlist_insert(data: {
    name: $name,
    description: $description,
    owner: { uid_expr: "auth.uid" }
  })
}

mutation AddTrackToPlaylist(
  $playlistId: String!,
  $trackId: String!
) @auth(level: USER) {
  playlistEntry_insert(data: {
    playlistId: $playlistId,
    trackId: $trackId
  })
}

mutation CreatePodcast(
  $name: String!,
  $publisher: String!,
  $imageUrl: String,
  $description: String
) @auth(level: PUBLIC) {
  podcast_insert(data: {
    name: $name,
    publisher: $publisher,
    imageUrl: $imageUrl,
    description: $description
  })
}
