android.useAndroidX=true
android.suppressUnsupportedCompileSdk=36
org.gradle.configuration-cache=false
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.enableR8.fullMode=true
android.enableGlobalSynthetics=false
android.builtInKotlin=false
android.newDsl=false
android.sync.suppressAgpWarnings=DEPRECATED_DSL,UNSUPPORTED_PROJECT_OPTION_USE
kotlin.native.ignoreDisabledTargets=true
