android.useAndroidX=true
android.suppressUnsupportedCompileSdk=35
org.gradle.configuration-cache=false
android.builtInKotlin=false
android.newDsl=false
org.gradle.jvmargs=-Xmx3072m -XX:MaxMetaspaceSize=1024m
android.sync.suppressAgpWarnings=UNSUPPORTED_PROJECT_OPTION_USE,DEPRECATED_DSL
android.dexing.enableGlobalSynthetics=false
kotlin.native.ignoreDisabledTargets=true
