import express from "express";
import path from "path";
import { fileURLToPath } from "url";
import { GoogleGenAI, Type } from "@google/genai";
import * as Sentry from "@sentry/node";
import dotenv from "dotenv";
import { initializeApp, getApps } from "firebase-admin/app";
import { getFirestore, FieldValue } from "firebase-admin/firestore";

import firebaseConfig from "./firebase-applet-config.json" with { type: "json" };

dotenv.config();

// Initialize Sentry Node SDK for backend crash tracking
Sentry.init({
  dsn: process.env.SENTRY_DSN || "https://a4cad24e9ec791b4987db15bf390d43f@o4511300849631232.ingest.us.sentry.io/4511703360339968",
  tracesSampleRate: 1.0,
  beforeSend(event) {
    // Sanitize any PII (authorization headers, keys, cookies) from requests
    if (event.request && event.request.headers) {
      delete event.request.headers["Authorization"];
      delete event.request.headers["authorization"];
      delete event.request.headers["Cookie"];
      delete event.request.headers["cookie"];
    }
    const sanitizeStr = (str: string): string => {
      return str.replace(/AQ\.[A-Za-z0-9_\-]+/g, "[REDACTED_API_KEY]")
                .replace(/AIzaSy[A-Za-z0-9_\-]+/g, "[REDACTED_API_KEY]");
    };
    if (event.exception && event.exception.values) {
      event.exception.values.forEach((val) => {
        if (val.value) val.value = sanitizeStr(val.value);
        if (val.stacktrace && val.stacktrace.frames) {
          val.stacktrace.frames.forEach((frame) => {
            if (frame.filename) frame.filename = sanitizeStr(frame.filename);
            if (frame.function) frame.function = sanitizeStr(frame.function);
          });
        }
      });
    }
    return event;
  }
});

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const app = express();
app.use(express.json());

// Sentry request handler must be first
Sentry.setupExpressErrorHandler(app);

// Initialize Gemini Client
const ai = new GoogleGenAI({
  apiKey: process.env.GEMINI_API_KEY,
  httpOptions: {
    headers: {
      "User-Agent": "aistudio-build",
    },
  },
});

// Initialize Firebase Admin SDK
if (!getApps().length) {
  initializeApp({
    projectId: firebaseConfig.projectId,
  });
}

const db = getFirestore();

// 1. Shifted Gemini requests server-side route
app.post("/api/generate", async (req, res, next) => {
  const { image } = req.body;
  if (!image) {
    res.status(400).json({ error: "Missing required 'image' field in request body." });
    return;
  }

  try {
    const systemPrompt = "You are a creative music director. Analyze the vibe, objects, and emotions in this image. Generate 3 short, evocative phrases, 4 to 5 words maximum per phrase, that can be used as prompts for an AI music generator. The phrases should describe genres, moods, instruments, or sound textures.";

    const response = await ai.models.generateContent({
      model: "gemini-3.5-flash",
      contents: {
        parts: [
          {
            inlineData: {
              mimeType: "image/jpeg",
              data: image,
            },
          },
          {
            text: systemPrompt,
          },
        ],
      },
      config: {
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            prompts: {
              type: Type.ARRAY,
              description: "A list of 3 creative music prompts.",
              items: {
                type: Type.STRING,
              },
            },
          },
        },
      },
    });

    const text = response.text;
    if (!text) {
      throw new Error("No response content generated by Gemini.");
    }

    const parsed = JSON.parse(text);
    res.json(parsed);
  } catch (err) {
    next(err);
  }
});

// Database API routes to capture wearables telemetry and gesture logs using Firestore
app.post("/api/logs/gesture", async (req, res, next) => {
  const { gesture } = req.body;
  if (!gesture) {
    res.status(400).json({ error: "Missing 'gesture' field." });
    return;
  }

  try {
    const docRef = await db.collection("gesture_logs").add({
      gesture,
      timestamp: FieldValue.serverTimestamp(),
    });
    res.status(201).json({ success: true, id: docRef.id });
  } catch (err) {
    next(err);
  }
});

app.post("/api/logs/battery", async (req, res, next) => {
  const { batteryLevel, isWearDetected } = req.body;
  if (batteryLevel === undefined || isWearDetected === undefined) {
    res.status(400).json({ error: "Missing 'batteryLevel' or 'isWearDetected' field." });
    return;
  }

  try {
    const docRef = await db.collection("battery_logs").add({
      batteryLevel: Number(batteryLevel),
      isWearDetected: String(isWearDetected),
      timestamp: FieldValue.serverTimestamp(),
    });
    res.status(201).json({ success: true, id: docRef.id });
  } catch (err) {
    next(err);
  }
});

app.post("/api/logs/prompt", async (req, res, next) => {
  const { prompt, weight } = req.body;
  if (!prompt || weight === undefined) {
    res.status(400).json({ error: "Missing 'prompt' or 'weight' field." });
    return;
  }

  try {
    const docRef = await db.collection("prompt_logs").add({
      prompt,
      weight: String(weight),
      timestamp: FieldValue.serverTimestamp(),
    });
    res.status(201).json({ success: true, id: docRef.id });
  } catch (err) {
    next(err);
  }
});

// Retrieve logs for status verification
app.get("/api/logs", async (req, res, next) => {
  try {
    const gesturesSnap = await db.collection("gesture_logs")
      .orderBy("timestamp", "desc")
      .limit(50)
      .get();
    
    const batteriesSnap = await db.collection("battery_logs")
      .orderBy("timestamp", "desc")
      .limit(50)
      .get();

    const gestures = gesturesSnap.docs.map(doc => {
      const data = doc.data();
      return {
        id: doc.id,
        gesture: data.gesture,
        timestamp: data.timestamp ? data.timestamp.toDate() : new Date(),
      };
    });

    const batteries = batteriesSnap.docs.map(doc => {
      const data = doc.data();
      return {
        id: doc.id,
        batteryLevel: data.batteryLevel,
        isWearDetected: data.isWearDetected,
        timestamp: data.timestamp ? data.timestamp.toDate() : new Date(),
      };
    });

    res.json({ gestures, batteries });
  } catch (err) {
    next(err);
  }
});

// Serve frontend static assets
app.use(express.static(path.join(__dirname, "dist")));

// Fallback to SPA routing for other frontend pages
app.get("*all", (req, res) => {
  res.sendFile(path.join(__dirname, "dist", "index.html"));
});

// Configure the default container PORT (3000)
const PORT = 3000;
app.listen(PORT, async () => {
  console.log(`Server started successfully on port ${PORT}`);
});
