import fs from 'fs';
import path from 'path';

const content = fs.readFileSync('server.ts', 'utf8');
const lines = content.split('\n');

const sliceLines = (start, end) => lines.slice(start - 1, end).join('\n');

// Ensure directories exist
fs.mkdirSync('server/middleware', { recursive: true });
fs.mkdirSync('server/routes', { recursive: true });

// Middlewares were generated by a previous script, but let's regenerate them to be safe.
// Wait, the python script generated them correctly.
// Let's generate the route files.

const commonImports = `import express from "express";
import { GoogleGenAI, Type } from "@google/genai";
import { getFirestore, FieldValue } from "firebase-admin/firestore";
import { getStorage } from "firebase-admin/storage";
import { AuthenticatedRequest } from "../middleware/auth.js";
import { verifyFirebaseToken } from "../middleware/auth.js";
import { verifyAppCheck } from "../middleware/appCheck.js";
import { checkDailyQuota } from "../middleware/quota.js";
import firebaseConfig from "../../firebase-applet-config.json" with { type: "json" };

const router = express.Router();
const db = getFirestore();
const ai = new GoogleGenAI({
  apiKey: process.env.GEMINI_API_KEY,
  httpOptions: {
    headers: {
      "User-Agent": "aistudio-build",
    },
  },
});
`;

// Define blocks
const routes = {
  webhooks: { start: 392, end: 659 },
  music: { start: 660, end: 833 },
  interactions: { start: 834, end: 1183 },
  logs: { start: 1184, end: 1290 },
  community: { start: 1291, end: 1444 },
  spotify: { start: 1445, end: 1908 },
  admin: { start: 1991, end: 2007 },
};

for (const [name, range] of Object.entries(routes)) {
  let routeContent = sliceLines(range.start, range.end);
  // Replace app.get, app.post with router.get, router.post
  routeContent = routeContent.replace(/^app\./gm, 'router.');
  
  if (name === 'admin') {
    // Remove the bypass in admin
    routeContent = routeContent.replace(
      /if\s*\(\s*req\.headers\.authorization\s*===\s*"Bearer super-secure-admin-token"\s*\)\s*\{\s*return\s+next\(\);\s*\}/g,
      ''
    );
  }
  
  fs.writeFileSync(`server/routes/${name}.ts`, commonImports + '\n' + routeContent + '\nexport default router;\n');
}

// Generate new server.ts
const newServerTs = `import express from "express";
import path from "path";
import { fileURLToPath } from "url";
import { GoogleGenAI } from "@google/genai";
import { WebSocketServer } from "ws";
import * as Sentry from "@sentry/node";
import dotenv from "dotenv";
import { initializeApp, getApps } from "firebase-admin/app";
import helmet from "helmet";
import compression from "compression";
import { SecretManagerServiceClient } from "@google-cloud/secret-manager";

import firebaseConfig from "./firebase-applet-config.json" with { type: "json" };

import { apiLimiter } from "./server/middleware/rateLimit.js";
import webhooksRouter from "./server/routes/webhooks.js";
import musicRouter from "./server/routes/music.js";
import interactionsRouter from "./server/routes/interactions.js";
import logsRouter from "./server/routes/logs.js";
import communityRouter from "./server/routes/community.js";
import spotifyRouter from "./server/routes/spotify.js";
import adminRouter from "./server/routes/admin.js";

dotenv.config();

const isGcpEnvironment = process.env.NODE_ENV === "production" || !!process.env.K_SERVICE || !!process.env.GOOGLE_APPLICATION_CREDENTIALS;

if (isGcpEnvironment) {
  const projectId = firebaseConfig.projectId;
  if (projectId) {
    try {
      console.log(\`GCP environment detected (Project: \${projectId}). Dynamic Secret Manager loading initiated...\`);
      const client = new SecretManagerServiceClient();

      try {
        const name = \`projects/\${projectId}/secrets/GEMINI_API_KEY/versions/latest\`;
        const [version] = await client.accessSecretVersion({ name });
        const payload = version.payload?.data?.toString()?.trim();
        if (payload) {
          process.env.GEMINI_API_KEY = payload;
          console.log("Successfully resolved and loaded GEMINI_API_KEY from Google Secret Manager.");
        }
      } catch (err: any) {
        console.warn(\`GEMINI_API_KEY not found in Google Secret Manager (falling back to environment): \${err.message || err}\`);
      }

      try {
        const name = \`projects/\${projectId}/secrets/SENTRY_DSN/versions/latest\`;
        const [version] = await client.accessSecretVersion({ name });
        const payload = version.payload?.data?.toString()?.trim();
        if (payload) {
          process.env.SENTRY_DSN = payload;
          console.log("Successfully resolved and loaded SENTRY_DSN from Google Secret Manager.");
        }
      } catch (err: any) {
        console.warn(\`SENTRY_DSN not found in Google Secret Manager (falling back to environment): \${err.message || err}\`);
      }
    } catch (err: any) {
      console.error(\`Failed to initialize Google Secret Manager client: \${err.message || err}. Falling back to standard env.\`);
    }
  }
}

const sentryDsn = process.env.SENTRY_DSN;
if (sentryDsn) {
  Sentry.init({
    dsn: sentryDsn,
    tracesSampleRate: 1.0,
    beforeSend(event) {
      if (event.request && event.request.headers) {
        delete event.request.headers["Authorization"];
        delete event.request.headers["authorization"];
        delete event.request.headers["Cookie"];
        delete event.request.headers["cookie"];
      }
      return event;
    }
  });
}

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const app = express();
app.use(express.json());

app.use(
  helmet({
    contentSecurityPolicy: false,
    crossOriginEmbedderPolicy: false,
    crossOriginOpenerPolicy: false,
    crossOriginResourcePolicy: false,
    frameguard: false,
  })
);

app.use(compression());
app.use("/api", apiLimiter);

if (!getApps().length) {
  initializeApp({
    projectId: firebaseConfig.projectId,
  });
}

// Routes
app.use(webhooksRouter);
app.use(musicRouter);
app.use(interactionsRouter);
app.use(logsRouter);
app.use(communityRouter);
app.use(spotifyRouter);
app.use(adminRouter);

${sliceLines(1909, 1990)}
${sliceLines(2008, 2121)}
`;

fs.writeFileSync('server.ts', newServerTs);
console.log("Refactoring complete");
