apply plugin: 'java'

repositories {
    google()
    mavenCentral()
    maven {
        url = uri("https://maven.pkg.github.com/facebook/meta-wearables-dat-android")
        credentials {
            username = System.getenv("GITHUB_ACTOR") ?: "GITHUB_ACTOR"
            def localProperties = new Properties()
            def localPropertiesFile = file('local.properties')
            if (localPropertiesFile.exists()) {
                localPropertiesFile.withInputStream { localProperties.load(it) }
            }
            password = System.getenv("GITHUB_TOKEN") ?: localProperties.getProperty("github_token")
        }
    }
}

configurations.all {
    resolutionStrategy.cacheDynamicVersionsFor 0, 'seconds'
}

dependencies {
    implementation 'com.meta.wearable:mwdat-core:+'
}

task printLatestVersion {
    doLast {
        configurations.compileClasspath.resolvedConfiguration.resolvedArtifacts.each { artifact ->
            if (artifact.moduleVersion.id.group == 'com.meta.wearable') {
                println "LATEST MWDAT VERSION: ${artifact.moduleVersion.id.version}"
            }
        }
    }
}
