import React, { useState, useEffect } from 'react';

export const CommunityStage: React.FC = () => {
  const [tracks, setTracks] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetch('/api/community/tracks')
      .then(res => res.json())
      .then(data => {
        setTracks(data.tracks || []);
        setLoading(false);
      })
      .catch(err => console.error("Failed to load community vibes", err));
  }, []);

  return (
    <div className="h-full p-8 overflow-y-auto bg-surface text-on-surface">
      <div className="max-w-6xl mx-auto space-y-12">
        <header className="space-y-4">
          <h2 className="text-5xl font-black tracking-tight italic">Community Stage</h2>
          <p className="text-on-surface-variant text-lg max-w-2xl font-medium">
            Explore live vibes generated by creators worldwide. Join the symphony and share your POV.
          </p>
        </header>

        {loading ? (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {[...Array(6)].map((_, i) => (
              <div key={i} className="aspect-square rounded-[2rem] bg-surface-container animate-pulse" />
            ))}
          </div>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            {tracks.map(track => (
              <TrackCard key={track.id} track={track} />
            ))}
          </div>
        )}
      </div>
    </div>
  );
};

const TrackCard: React.FC<{ track: any }> = ({ track }) => (
  <div className="group relative aspect-square rounded-[2rem] overflow-hidden bg-surface-container border border-outline/10 hover:border-primary/50 transition-all duration-500 shadow-xl hover:shadow-primary/20">
    <img
      src={track.imageUrl || 'https://images.unsplash.com/photo-1614613535308-eb5fbd3d2c17?auto=format&fit=crop&q=80&w=320'}
      className="w-full h-full object-cover transition-transform duration-700 group-hover:scale-110 opacity-60 group-hover:opacity-100"
      alt={track.title}
    />

    <div className="absolute inset-0 bg-gradient-to-t from-surface via-surface/20 to-transparent p-6 flex flex-col justify-end">
      <div className="space-y-1 transform transition-transform duration-500 group-hover:-translate-y-2">
        <h4 className="text-2xl font-bold leading-tight">{track.title}</h4>
        <p className="text-primary font-bold text-sm tracking-wide uppercase">{track.artist}</p>
        <p className="text-on-surface-variant text-xs line-clamp-2 mt-2 font-medium opacity-0 group-hover:opacity-100 transition-opacity">
          {track.vibe}
        </p>
      </div>

      <button className="mt-4 w-full py-3 bg-primary text-on-primary rounded-2xl font-black text-sm uppercase tracking-widest opacity-0 group-hover:opacity-100 transition-all transform translate-y-4 group-hover:translate-y-0 hover:brightness-110">
        Sync to Wearables
      </button>
    </div>

    <div className="absolute top-4 right-4 px-3 py-1 bg-surface/60 backdrop-blur-md rounded-full border border-outline/10 flex items-center gap-2">
      <span className="w-2 h-2 rounded-full bg-error animate-pulse" />
      <span className="text-[10px] font-bold uppercase tracking-tighter">Live POV</span>
    </div>
  </div>
);
