extend type BookmarkedTrack {
  """
  ✨ Implicit foreign key field based on `BookmarkedTrack`.`user`. It must match the value of `User`.`uid`. See `@ref` for how to customize it.
  """
  userUid: String! @fdc_generated(from: "BookmarkedTrack.user", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `BookmarkedTrack`.`track`. It must match the value of `Track`.`id`. See `@ref` for how to customize it.
  """
  trackId: String! @fdc_generated(from: "BookmarkedTrack.track", purpose: IMPLICIT_REF_FIELD)
}
extend type LikedTrack {
  """
  ✨ Implicit foreign key field based on `LikedTrack`.`user`. It must match the value of `User`.`uid`. See `@ref` for how to customize it.
  """
  userUid: String! @fdc_generated(from: "LikedTrack.user", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `LikedTrack`.`track`. It must match the value of `Track`.`id`. See `@ref` for how to customize it.
  """
  trackId: String! @fdc_generated(from: "LikedTrack.track", purpose: IMPLICIT_REF_FIELD)
}
extend type PaymentHistory {
  """
  ✨ Implicit foreign key field based on `PaymentHistory`.`user`. It must match the value of `User`.`uid`. See `@ref` for how to customize it.
  """
  userUid: String! @fdc_generated(from: "PaymentHistory.user", purpose: IMPLICIT_REF_FIELD)
}
extend type Playlist {
  """
  ✨ Implicit foreign key field based on `Playlist`.`owner`. It must match the value of `User`.`uid`. See `@ref` for how to customize it.
  """
  ownerUid: String! @fdc_generated(from: "Playlist.owner", purpose: IMPLICIT_REF_FIELD)
}
extend type PlaylistEntry {
  """
  ✨ Implicit foreign key field based on `PlaylistEntry`.`playlist`. It must match the value of `Playlist`.`id`. See `@ref` for how to customize it.
  """
  playlistId: String! @fdc_generated(from: "PlaylistEntry.playlist", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `PlaylistEntry`.`track`. It must match the value of `Track`.`id`. See `@ref` for how to customize it.
  """
  trackId: String! @fdc_generated(from: "PlaylistEntry.track", purpose: IMPLICIT_REF_FIELD)
}
extend type PodcastEpisode {
  """
  ✨ Implicit foreign key field based on `PodcastEpisode`.`podcast`. It must match the value of `Podcast`.`id`. See `@ref` for how to customize it.
  """
  podcastId: String! @fdc_generated(from: "PodcastEpisode.podcast", purpose: IMPLICIT_REF_FIELD)
}
extend type Track {
  """
  ✨ Implicit foreign key field based on `Track`.`owner`. It must match the value of `User`.`uid`. See `@ref` for how to customize it.
  """
  ownerUid: String! @fdc_generated(from: "Track.owner", purpose: IMPLICIT_REF_FIELD)
}
extend type UserSettings {
  """
  ✨ Implicit foreign key field based on `UserSettings`.`user`. It must match the value of `User`.`uid`. See `@ref` for how to customize it.
  """
  userUid: String! @fdc_generated(from: "UserSettings.user", purpose: IMPLICIT_REF_FIELD)
}
