extend type Query {
  """
  ✨ Look up a single `Album` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  album(
    """
    The unique ID of the object.
    """
    id: String

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: String_Expr

    """
    The key used to identify the object.
    """
    key: Album_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Album_FirstRow
  ): Album @fdc_generated(from: "Album", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Audiobook` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  audiobook(
    """
    The unique ID of the object.
    """
    id: String

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: String_Expr

    """
    The key used to identify the object.
    """
    key: Audiobook_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Audiobook_FirstRow
  ): Audiobook @fdc_generated(from: "Audiobook", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `BookmarkedTrack` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  bookmarkedTrack(
    """
    The key used to identify the object.
    """
    key: BookmarkedTrack_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: BookmarkedTrack_FirstRow
  ): BookmarkedTrack @fdc_generated(from: "BookmarkedTrack", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Category` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  category(
    """
    The unique ID of the object.
    """
    id: String

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: String_Expr

    """
    The key used to identify the object.
    """
    key: Category_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Category_FirstRow
  ): Category @fdc_generated(from: "Category", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `LikedTrack` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  likedTrack(
    """
    The key used to identify the object.
    """
    key: LikedTrack_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: LikedTrack_FirstRow
  ): LikedTrack @fdc_generated(from: "LikedTrack", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `PaymentHistory` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  paymentHistory(
    """
    The unique ID of the object.
    """
    id: String

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: String_Expr

    """
    The key used to identify the object.
    """
    key: PaymentHistory_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: PaymentHistory_FirstRow
  ): PaymentHistory @fdc_generated(from: "PaymentHistory", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Playlist` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  playlist(
    """
    The unique ID of the object.
    """
    id: String

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: String_Expr

    """
    The key used to identify the object.
    """
    key: Playlist_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Playlist_FirstRow
  ): Playlist @fdc_generated(from: "Playlist", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `PlaylistEntry` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  playlistEntry(
    """
    The key used to identify the object.
    """
    key: PlaylistEntry_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: PlaylistEntry_FirstRow
  ): PlaylistEntry @fdc_generated(from: "PlaylistEntry", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Podcast` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  podcast(
    """
    The unique ID of the object.
    """
    id: String

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: String_Expr

    """
    The key used to identify the object.
    """
    key: Podcast_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Podcast_FirstRow
  ): Podcast @fdc_generated(from: "Podcast", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `PodcastEpisode` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  podcastEpisode(
    """
    The unique ID of the object.
    """
    id: String

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: String_Expr

    """
    The key used to identify the object.
    """
    key: PodcastEpisode_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: PodcastEpisode_FirstRow
  ): PodcastEpisode @fdc_generated(from: "PodcastEpisode", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Track` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  track(
    """
    The unique ID of the object.
    """
    id: String

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: String_Expr

    """
    The key used to identify the object.
    """
    key: Track_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Track_FirstRow
  ): Track @fdc_generated(from: "Track", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `User` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  user(
    """
    The key used to identify the object.
    """
    key: User_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: User_FirstRow
  ): User @fdc_generated(from: "User", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `UserSettings` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  userSettings(
    """
    The key used to identify the object.
    """
    key: UserSettings_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: UserSettings_FirstRow
  ): UserSettings @fdc_generated(from: "UserSettings", purpose: QUERY_SINGLE)
  """
  ✨ List `Album` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  albums(
    """
    Filter condition to narrow down the query results.
    """
    where: Album_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Album_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Album_Having
  ): [Album!]! @fdc_generated(from: "Album", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Audiobook` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  audiobooks(
    """
    Filter condition to narrow down the query results.
    """
    where: Audiobook_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Audiobook_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Audiobook_Having
  ): [Audiobook!]! @fdc_generated(from: "Audiobook", purpose: QUERY_MULTIPLE)
  """
  ✨ List `BookmarkedTrack` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  bookmarkedTracks(
    """
    Filter condition to narrow down the query results.
    """
    where: BookmarkedTrack_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [BookmarkedTrack_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: BookmarkedTrack_Having
  ): [BookmarkedTrack!]! @fdc_generated(from: "BookmarkedTrack", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Category` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  categories(
    """
    Filter condition to narrow down the query results.
    """
    where: Category_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Category_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Category_Having
  ): [Category!]! @fdc_generated(from: "Category", purpose: QUERY_MULTIPLE)
  """
  ✨ List `LikedTrack` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  likedTracks(
    """
    Filter condition to narrow down the query results.
    """
    where: LikedTrack_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [LikedTrack_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: LikedTrack_Having
  ): [LikedTrack!]! @fdc_generated(from: "LikedTrack", purpose: QUERY_MULTIPLE)
  """
  ✨ List `PaymentHistory` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  paymentHistories(
    """
    Filter condition to narrow down the query results.
    """
    where: PaymentHistory_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [PaymentHistory_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: PaymentHistory_Having
  ): [PaymentHistory!]! @fdc_generated(from: "PaymentHistory", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Playlist` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  playlists(
    """
    Filter condition to narrow down the query results.
    """
    where: Playlist_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Playlist_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Playlist_Having
  ): [Playlist!]! @fdc_generated(from: "Playlist", purpose: QUERY_MULTIPLE)
  """
  ✨ List `PlaylistEntry` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  playlistEntries(
    """
    Filter condition to narrow down the query results.
    """
    where: PlaylistEntry_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [PlaylistEntry_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: PlaylistEntry_Having
  ): [PlaylistEntry!]! @fdc_generated(from: "PlaylistEntry", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Podcast` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  podcasts(
    """
    Filter condition to narrow down the query results.
    """
    where: Podcast_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Podcast_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Podcast_Having
  ): [Podcast!]! @fdc_generated(from: "Podcast", purpose: QUERY_MULTIPLE)
  """
  ✨ List `PodcastEpisode` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  podcastEpisodes(
    """
    Filter condition to narrow down the query results.
    """
    where: PodcastEpisode_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [PodcastEpisode_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: PodcastEpisode_Having
  ): [PodcastEpisode!]! @fdc_generated(from: "PodcastEpisode", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Track` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  tracks(
    """
    Filter condition to narrow down the query results.
    """
    where: Track_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Track_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Track_Having
  ): [Track!]! @fdc_generated(from: "Track", purpose: QUERY_MULTIPLE)
  """
  ✨ List `User` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  users(
    """
    Filter condition to narrow down the query results.
    """
    where: User_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [User_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: User_Having
  ): [User!]! @fdc_generated(from: "User", purpose: QUERY_MULTIPLE)
  """
  ✨ List `UserSettings` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  userSettingss(
    """
    Filter condition to narrow down the query results.
    """
    where: UserSettings_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [UserSettings_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: UserSettings_Having
  ): [UserSettings!]! @fdc_generated(from: "UserSettings", purpose: QUERY_MULTIPLE)
}
