extend type Album {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Album", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Album` table.
  """
  _count: Int! @fdc_generated(from: "Album.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Album` table where the `artistName` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  artistName_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Album.artistName", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Album` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Album.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Album` table where the `imageUrl` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  imageUrl_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Album.imageUrl", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Album` table where the `name` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  name_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Album.name", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Album` table where the `releaseYear` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  releaseYear_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Album.releaseYear", purpose: QUERY_COUNT)
  """
  ✨ Sum the `releaseYear` field in the `Album` table.
  """
  releaseYear_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Int @fdc_generated(from: "Album.releaseYear", purpose: QUERY_SUM)
  """
  ✨ Average the `releaseYear` field in the `Album` table.
  """
  releaseYear_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Album.releaseYear", purpose: QUERY_AVG)
  """
  ✨ Minimum of the `releaseYear` field in the `Album` table.
  """
  releaseYear_min: Int @fdc_generated(from: "Album.releaseYear", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `releaseYear` field in the `Album` table.
  """
  releaseYear_max: Int @fdc_generated(from: "Album.releaseYear", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Album.id", purpose: ENTITY_ID)
}
extend type Audiobook {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Audiobook", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Audiobook` table.
  """
  _count: Int! @fdc_generated(from: "Audiobook.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Audiobook` table where the `audioUrl` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  audioUrl_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Audiobook.audioUrl", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Audiobook` table where the `author` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  author_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Audiobook.author", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Audiobook` table where the `duration` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  duration_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Audiobook.duration", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Audiobook` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Audiobook.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Audiobook` table where the `imageUrl` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  imageUrl_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Audiobook.imageUrl", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Audiobook` table where the `narrator` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  narrator_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Audiobook.narrator", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Audiobook` table where the `title` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  title_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Audiobook.title", purpose: QUERY_COUNT)
  """
  ✨ Sum the `duration` field in the `Audiobook` table.
  """
  duration_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Int @fdc_generated(from: "Audiobook.duration", purpose: QUERY_SUM)
  """
  ✨ Average the `duration` field in the `Audiobook` table.
  """
  duration_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Audiobook.duration", purpose: QUERY_AVG)
  """
  ✨ Minimum of the `duration` field in the `Audiobook` table.
  """
  duration_min: Int @fdc_generated(from: "Audiobook.duration", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `duration` field in the `Audiobook` table.
  """
  duration_max: Int @fdc_generated(from: "Audiobook.duration", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Audiobook.id", purpose: ENTITY_ID)
}
extend type BookmarkedTrack {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "BookmarkedTrack", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `BookmarkedTrack` table.
  """
  _count: Int! @fdc_generated(from: "BookmarkedTrack.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `BookmarkedTrack` table where the `addedAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  addedAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "BookmarkedTrack.addedAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `BookmarkedTrack` table where the `trackId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  trackId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "BookmarkedTrack.trackId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `BookmarkedTrack` table where the `userUid` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  userUid_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "BookmarkedTrack.userUid", purpose: QUERY_COUNT)
  """
  ✨ Minimum of the `addedAt` field in the `BookmarkedTrack` table.
  """
  addedAt_min: Timestamp @fdc_generated(from: "BookmarkedTrack.addedAt", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `addedAt` field in the `BookmarkedTrack` table.
  """
  addedAt_max: Timestamp @fdc_generated(from: "BookmarkedTrack.addedAt", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "BookmarkedTrack.userUid,trackId", purpose: ENTITY_ID)
}
extend type Category {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Category", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Category` table.
  """
  _count: Int! @fdc_generated(from: "Category.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Category` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Category.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Category` table where the `imageUrl` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  imageUrl_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Category.imageUrl", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Category` table where the `name` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  name_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Category.name", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Category` table where the `type` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  type_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Category.type", purpose: QUERY_COUNT)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Category.id", purpose: ENTITY_ID)
}
extend type LikedTrack {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "LikedTrack", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `LikedTrack` table.
  """
  _count: Int! @fdc_generated(from: "LikedTrack.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `LikedTrack` table where the `addedAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  addedAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "LikedTrack.addedAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `LikedTrack` table where the `trackId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  trackId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "LikedTrack.trackId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `LikedTrack` table where the `userUid` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  userUid_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "LikedTrack.userUid", purpose: QUERY_COUNT)
  """
  ✨ Minimum of the `addedAt` field in the `LikedTrack` table.
  """
  addedAt_min: Timestamp @fdc_generated(from: "LikedTrack.addedAt", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `addedAt` field in the `LikedTrack` table.
  """
  addedAt_max: Timestamp @fdc_generated(from: "LikedTrack.addedAt", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "LikedTrack.userUid,trackId", purpose: ENTITY_ID)
}
extend type PaymentHistory {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "PaymentHistory", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `PaymentHistory` table.
  """
  _count: Int! @fdc_generated(from: "PaymentHistory.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `PaymentHistory` table where the `amount` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  amount_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "PaymentHistory.amount", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `PaymentHistory` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "PaymentHistory.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `PaymentHistory` table where the `currency` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  currency_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "PaymentHistory.currency", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `PaymentHistory` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "PaymentHistory.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `PaymentHistory` table where the `status` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  status_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "PaymentHistory.status", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `PaymentHistory` table where the `stripeInvoiceId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  stripeInvoiceId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "PaymentHistory.stripeInvoiceId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `PaymentHistory` table where the `userUid` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  userUid_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "PaymentHistory.userUid", purpose: QUERY_COUNT)
  """
  ✨ Sum the `amount` field in the `PaymentHistory` table.
  """
  amount_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "PaymentHistory.amount", purpose: QUERY_SUM)
  """
  ✨ Average the `amount` field in the `PaymentHistory` table.
  """
  amount_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "PaymentHistory.amount", purpose: QUERY_AVG)
  """
  ✨ Minimum of the `amount` field in the `PaymentHistory` table.
  """
  amount_min: Float @fdc_generated(from: "PaymentHistory.amount", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `createdAt` field in the `PaymentHistory` table.
  """
  createdAt_min: Timestamp @fdc_generated(from: "PaymentHistory.createdAt", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `amount` field in the `PaymentHistory` table.
  """
  amount_max: Float @fdc_generated(from: "PaymentHistory.amount", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `createdAt` field in the `PaymentHistory` table.
  """
  createdAt_max: Timestamp @fdc_generated(from: "PaymentHistory.createdAt", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "PaymentHistory.id", purpose: ENTITY_ID)
}
extend type Playlist {
  """
  ✨ List `PlaylistEntry` objects in a one-to-many relationship (where `PlaylistEntry`.`playlist` is this object).
  """
  playlistEntries_on_playlist(
    """
    Filter condition to narrow down the query results.
    """
    where: PlaylistEntry_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [PlaylistEntry_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: PlaylistEntry_Having
  ): [PlaylistEntry!]! @fdc_generated(from: "PlaylistEntry.playlist", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `Track` objects using `PlaylistEntry` as the join table (a `PlaylistEntry` object exists where its `playlist` is this and its `track` is that).
  """
  tracks_via_PlaylistEntry(
    """
    Filter condition to narrow down the query results.
    """
    where: PlaylistEntry_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [PlaylistEntry_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: PlaylistEntry_Having
  ): [Track!]! @fdc_generated(from: "PlaylistEntry", purpose: QUERY_MULTIPLE_MANY_TO_MANY)
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Playlist", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Playlist` table.
  """
  _count: Int! @fdc_generated(from: "Playlist.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Playlist` table where the `description` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  description_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Playlist.description", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Playlist` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Playlist.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Playlist` table where the `imageUrl` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  imageUrl_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Playlist.imageUrl", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Playlist` table where the `isPublic` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  isPublic_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Playlist.isPublic", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Playlist` table where the `name` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  name_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Playlist.name", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Playlist` table where the `ownerUid` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  ownerUid_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Playlist.ownerUid", purpose: QUERY_COUNT)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Playlist.id", purpose: ENTITY_ID)
}
extend type PlaylistEntry {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "PlaylistEntry", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `PlaylistEntry` table.
  """
  _count: Int! @fdc_generated(from: "PlaylistEntry.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `PlaylistEntry` table where the `addedAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  addedAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "PlaylistEntry.addedAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `PlaylistEntry` table where the `playlistId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  playlistId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "PlaylistEntry.playlistId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `PlaylistEntry` table where the `trackId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  trackId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "PlaylistEntry.trackId", purpose: QUERY_COUNT)
  """
  ✨ Minimum of the `addedAt` field in the `PlaylistEntry` table.
  """
  addedAt_min: Timestamp @fdc_generated(from: "PlaylistEntry.addedAt", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `addedAt` field in the `PlaylistEntry` table.
  """
  addedAt_max: Timestamp @fdc_generated(from: "PlaylistEntry.addedAt", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "PlaylistEntry.playlistId,trackId", purpose: ENTITY_ID)
}
extend type Podcast {
  """
  ✨ List `PodcastEpisode` objects in a one-to-many relationship (where `PodcastEpisode`.`podcast` is this object).
  """
  podcastEpisodes_on_podcast(
    """
    Filter condition to narrow down the query results.
    """
    where: PodcastEpisode_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [PodcastEpisode_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: PodcastEpisode_Having
  ): [PodcastEpisode!]! @fdc_generated(from: "PodcastEpisode.podcast", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Podcast", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Podcast` table.
  """
  _count: Int! @fdc_generated(from: "Podcast.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Podcast` table where the `description` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  description_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Podcast.description", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Podcast` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Podcast.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Podcast` table where the `imageUrl` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  imageUrl_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Podcast.imageUrl", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Podcast` table where the `name` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  name_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Podcast.name", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Podcast` table where the `publisher` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  publisher_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Podcast.publisher", purpose: QUERY_COUNT)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Podcast.id", purpose: ENTITY_ID)
}
extend type PodcastEpisode {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "PodcastEpisode", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `PodcastEpisode` table.
  """
  _count: Int! @fdc_generated(from: "PodcastEpisode.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `PodcastEpisode` table where the `audioUrl` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  audioUrl_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "PodcastEpisode.audioUrl", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `PodcastEpisode` table where the `duration` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  duration_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "PodcastEpisode.duration", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `PodcastEpisode` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "PodcastEpisode.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `PodcastEpisode` table where the `podcastId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  podcastId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "PodcastEpisode.podcastId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `PodcastEpisode` table where the `publishDate` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  publishDate_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "PodcastEpisode.publishDate", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `PodcastEpisode` table where the `title` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  title_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "PodcastEpisode.title", purpose: QUERY_COUNT)
  """
  ✨ Sum the `duration` field in the `PodcastEpisode` table.
  """
  duration_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Int @fdc_generated(from: "PodcastEpisode.duration", purpose: QUERY_SUM)
  """
  ✨ Average the `duration` field in the `PodcastEpisode` table.
  """
  duration_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "PodcastEpisode.duration", purpose: QUERY_AVG)
  """
  ✨ Minimum of the `duration` field in the `PodcastEpisode` table.
  """
  duration_min: Int @fdc_generated(from: "PodcastEpisode.duration", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `publishDate` field in the `PodcastEpisode` table.
  """
  publishDate_min: Timestamp @fdc_generated(from: "PodcastEpisode.publishDate", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `duration` field in the `PodcastEpisode` table.
  """
  duration_max: Int @fdc_generated(from: "PodcastEpisode.duration", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `publishDate` field in the `PodcastEpisode` table.
  """
  publishDate_max: Timestamp @fdc_generated(from: "PodcastEpisode.publishDate", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "PodcastEpisode.id", purpose: ENTITY_ID)
}
extend type Track {
  """
  ✨ List `BookmarkedTrack` objects in a one-to-many relationship (where `BookmarkedTrack`.`track` is this object).
  """
  bookmarkedTracks_on_track(
    """
    Filter condition to narrow down the query results.
    """
    where: BookmarkedTrack_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [BookmarkedTrack_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: BookmarkedTrack_Having
  ): [BookmarkedTrack!]! @fdc_generated(from: "BookmarkedTrack.track", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `LikedTrack` objects in a one-to-many relationship (where `LikedTrack`.`track` is this object).
  """
  likedTracks_on_track(
    """
    Filter condition to narrow down the query results.
    """
    where: LikedTrack_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [LikedTrack_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: LikedTrack_Having
  ): [LikedTrack!]! @fdc_generated(from: "LikedTrack.track", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `PlaylistEntry` objects in a one-to-many relationship (where `PlaylistEntry`.`track` is this object).
  """
  playlistEntries_on_track(
    """
    Filter condition to narrow down the query results.
    """
    where: PlaylistEntry_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [PlaylistEntry_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: PlaylistEntry_Having
  ): [PlaylistEntry!]! @fdc_generated(from: "PlaylistEntry.track", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `Playlist` objects using `PlaylistEntry` as the join table (a `PlaylistEntry` object exists where its `track` is this and its `playlist` is that).
  """
  playlists_via_PlaylistEntry(
    """
    Filter condition to narrow down the query results.
    """
    where: PlaylistEntry_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [PlaylistEntry_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: PlaylistEntry_Having
  ): [Playlist!]! @fdc_generated(from: "PlaylistEntry", purpose: QUERY_MULTIPLE_MANY_TO_MANY)
  """
  ✨ List `User` objects using `BookmarkedTrack` as the join table (a `BookmarkedTrack` object exists where its `track` is this and its `user` is that).
  """
  users_via_BookmarkedTrack(
    """
    Filter condition to narrow down the query results.
    """
    where: BookmarkedTrack_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [BookmarkedTrack_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: BookmarkedTrack_Having
  ): [User!]! @fdc_generated(from: "BookmarkedTrack", purpose: QUERY_MULTIPLE_MANY_TO_MANY)
  """
  ✨ List `User` objects using `LikedTrack` as the join table (a `LikedTrack` object exists where its `track` is this and its `user` is that).
  """
  users_via_LikedTrack(
    """
    Filter condition to narrow down the query results.
    """
    where: LikedTrack_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [LikedTrack_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: LikedTrack_Having
  ): [User!]! @fdc_generated(from: "LikedTrack", purpose: QUERY_MULTIPLE_MANY_TO_MANY)
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Track", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Track` table.
  """
  _count: Int! @fdc_generated(from: "Track.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Track` table where the `albumName` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  albumName_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Track.albumName", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Track` table where the `artistName` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  artistName_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Track.artistName", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Track` table where the `audioUrl` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  audioUrl_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Track.audioUrl", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Track` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Track.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Track` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Track.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Track` table where the `imageUrl` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  imageUrl_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Track.imageUrl", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Track` table where the `isCommunity` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  isCommunity_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Track.isCommunity", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Track` table where the `name` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  name_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Track.name", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Track` table where the `ownerUid` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  ownerUid_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Track.ownerUid", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Track` table where the `prompt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  prompt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Track.prompt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Track` table where the `visibility` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  visibility_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Track.visibility", purpose: QUERY_COUNT)
  """
  ✨ Minimum of the `createdAt` field in the `Track` table.
  """
  createdAt_min: Timestamp @fdc_generated(from: "Track.createdAt", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `createdAt` field in the `Track` table.
  """
  createdAt_max: Timestamp @fdc_generated(from: "Track.createdAt", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Track.id", purpose: ENTITY_ID)
}
extend type User {
  """
  ✨ List `BookmarkedTrack` objects in a one-to-many relationship (where `BookmarkedTrack`.`user` is this object).
  """
  bookmarkedTracks_on_user(
    """
    Filter condition to narrow down the query results.
    """
    where: BookmarkedTrack_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [BookmarkedTrack_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: BookmarkedTrack_Having
  ): [BookmarkedTrack!]! @fdc_generated(from: "BookmarkedTrack.user", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `LikedTrack` objects in a one-to-many relationship (where `LikedTrack`.`user` is this object).
  """
  likedTracks_on_user(
    """
    Filter condition to narrow down the query results.
    """
    where: LikedTrack_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [LikedTrack_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: LikedTrack_Having
  ): [LikedTrack!]! @fdc_generated(from: "LikedTrack.user", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `PaymentHistory` objects in a one-to-many relationship (where `PaymentHistory`.`user` is this object).
  """
  paymentHistories_on_user(
    """
    Filter condition to narrow down the query results.
    """
    where: PaymentHistory_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [PaymentHistory_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: PaymentHistory_Having
  ): [PaymentHistory!]! @fdc_generated(from: "PaymentHistory.user", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `Playlist` objects in a one-to-many relationship (where `Playlist`.`owner` is this object).
  """
  playlists_on_owner(
    """
    Filter condition to narrow down the query results.
    """
    where: Playlist_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Playlist_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Playlist_Having
  ): [Playlist!]! @fdc_generated(from: "Playlist.owner", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `Track` objects in a one-to-many relationship (where `Track`.`owner` is this object).
  """
  tracks_on_owner(
    """
    Filter condition to narrow down the query results.
    """
    where: Track_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Track_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Track_Having
  ): [Track!]! @fdc_generated(from: "Track.owner", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `UserSettings` objects in a one-to-one relationship (where `UserSettings`.`user` is this object).
  """
  userSettings_on_user: UserSettings @fdc_generated(from: "UserSettings.user", purpose: QUERY_SINGLE_ONE_TO_ONE)
  """
  ✨ List `Track` objects using `BookmarkedTrack` as the join table (a `BookmarkedTrack` object exists where its `user` is this and its `track` is that).
  """
  tracks_via_BookmarkedTrack(
    """
    Filter condition to narrow down the query results.
    """
    where: BookmarkedTrack_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [BookmarkedTrack_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: BookmarkedTrack_Having
  ): [Track!]! @fdc_generated(from: "BookmarkedTrack", purpose: QUERY_MULTIPLE_MANY_TO_MANY)
  """
  ✨ List `Track` objects using `LikedTrack` as the join table (a `LikedTrack` object exists where its `user` is this and its `track` is that).
  """
  tracks_via_LikedTrack(
    """
    Filter condition to narrow down the query results.
    """
    where: LikedTrack_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [LikedTrack_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: LikedTrack_Having
  ): [Track!]! @fdc_generated(from: "LikedTrack", purpose: QUERY_MULTIPLE_MANY_TO_MANY)
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "User", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `User` table.
  """
  _count: Int! @fdc_generated(from: "User.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `avatarUrl` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  avatarUrl_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.avatarUrl", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `displayName` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  displayName_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.displayName", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `email` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  email_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.email", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `uid` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  uid_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.uid", purpose: QUERY_COUNT)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "User.uid", purpose: ENTITY_ID)
}
extend type UserSettings {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "UserSettings", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `UserSettings` table.
  """
  _count: Int! @fdc_generated(from: "UserSettings.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `UserSettings` table where the `isPremium` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  isPremium_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "UserSettings.isPremium", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `UserSettings` table where the `parentalControlsEnabled` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  parentalControlsEnabled_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "UserSettings.parentalControlsEnabled", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `UserSettings` table where the `stripeCustomerId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  stripeCustomerId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "UserSettings.stripeCustomerId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `UserSettings` table where the `theme` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  theme_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "UserSettings.theme", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `UserSettings` table where the `userId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  userId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "UserSettings.userId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `UserSettings` table where the `userUid` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  userUid_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "UserSettings.userUid", purpose: QUERY_COUNT)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "UserSettings.userId", purpose: ENTITY_ID)
}
