import React, { useState, useEffect, useRef } from 'react';
import { Typography } from '../../components/atoms/Typography';
import { Icon } from '../../components/atoms/Icon';
import { narrativeService } from '../../services/narrativeService';
import { useAppContext } from '../../contexts/AppContext';
import { logger } from "../../lib/logger";
import { musicService } from '../../services/MusicService';
import { ErrorAlert } from '../../components/molecules/ErrorAlert';
import { Shimmer } from '../../components/atoms/Shimmer';

export const PodcastGeneratorScreen: React.FC = () => {
  const [prompt, setPrompt] = useState('');
  const [selectedVoice] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [podcastResult, setPodcastResult] = useState<any | null>(null);
  const [thinkingText, setThinkingText] = useState('');
  const { setCurrentTrack, setIsPlaying } = useAppContext();

  const [isRecording, setIsRecording] = useState(false);
  const recognitionRef = useRef<any>(null);

  useEffect(() => {
    const SpeechRecognition = (window as any).SpeechRecognition || (window as any).webkitSpeechRecognition;
    if (SpeechRecognition) {
      const recognition = new SpeechRecognition();
      recognition.continuous = false;
      recognition.interimResults = true;
      
      recognition.onresult = (event: any) => {
        const transcript = Array.from(event.results)
          .map((result: any) => result[0].transcript)
          .join('');
        setPrompt(transcript);
      };
      
      recognition.onend = () => {
        setIsRecording(false);
      };
      
      recognitionRef.current = recognition;
    }
  }, []);

  const toggleRecording = () => {
    if (isRecording) {
      recognitionRef.current?.stop();
      setIsRecording(false);
    } else {
      if (recognitionRef.current) {
        setPrompt('');
        recognitionRef.current.start();
        setIsRecording(true);
      } else {
        window.dispatchEvent(new CustomEvent('show-toast', { detail: 'Speech recognition not supported in this browser' }));
      }
    }
  };

  const handleAction = async (action: 'like' | 'share', targetId?: string) => {
    if (!targetId) return;
    if ('vibrate' in navigator) navigator.vibrate([50, 50, 50]);
    try {
      if (action === 'like') {
        await musicService.likeItem(targetId, 'podcast');
        window.dispatchEvent(new CustomEvent('show-toast', { detail: 'Podcast saved to library!' }));
      } else if (action === 'share') {
        const url = `${window.location.origin}/podcast`;
        if (navigator.share) {
          navigator.share({
            title: 'Mave Podcast',
            text: 'Listen to this podcast generated by Mave!',
            url: url
          }).catch(console.error);
        } else {
          navigator.clipboard.writeText(url);
          window.dispatchEvent(new CustomEvent('show-toast', { detail: 'Share link copied to clipboard!' }));
        }
      }
    } catch (err) {
      window.dispatchEvent(new CustomEvent('show-toast', { detail: 'Failed to complete action' }));
    }
  };


  const handleGenerate = async () => {
    if (!prompt.trim()) {
      setError('Please enter a topic or concept for your podcast.');
      return;
    }
    setError(null);
    setPodcastResult(null);
    setThinkingText('');
    setLoading(true);

    try {
      const response = await narrativeService.generatePodcast(prompt, selectedVoice);

      const reader = response.body?.getReader();
      const decoder = new TextDecoder();
      let done = false;
      let scriptBuffer = '';
      let streamBuffer = '';
      
      const { AudioStreamPlayer } = await import('../../utils/AudioStreamPlayer');
      const audioPlayer = new AudioStreamPlayer();
      await audioPlayer.init();

      while (!done && reader) {
        const { value, done: doneReading } = await reader.read();
        done = doneReading;
        if (value) {
          const chunkStr = decoder.decode(value, { stream: true });
          streamBuffer += chunkStr;
          
          let eolIndex;
          while ((eolIndex = streamBuffer.indexOf('\n\n')) >= 0) {
            const line = streamBuffer.slice(0, eolIndex).trim();
            streamBuffer = streamBuffer.slice(eolIndex + 2);
            
            if (line.startsWith('data: ')) {
              try {
                const data = JSON.parse(line.substring(6));
                if (data.type === 'chunk' || data.type === 'thought') {
                  scriptBuffer += data.text;
                  setThinkingText(scriptBuffer);
                } else if (data.type === 'audio_chunk') {
                  audioPlayer.queueAudioChunk(data.data);
                } else if (data.type === 'complete') {
                  setPodcastResult(data.track);
                  setCurrentTrack(data.track);
                  setIsPlaying(true);
                  setThinkingText('');
                } else if (data.type === 'error') {
                  setError(data.error);
                  setThinkingText('');
                  audioPlayer.stop();
                }
              } catch (e) {
                logger.error("Failed to parse SSE data", e);
              }
            }
          }
        }
      }
      
      // Fallback or disconnect recovery if streaming drops midway
      if (!done && scriptBuffer.length > 0 && !podcastResult) {
        setError('Stream interrupted. Please try generating again.');
        setThinkingText('');
      }
    } catch (err: any) {
      logger.error('[PODCAST] Generation error:', err);
      setError('Unable to load podcast right now. Please try again later.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="flex flex-col h-full w-full bg-background overflow-y-auto p-4 pb-32 gap-6">
      <div className="flex items-center gap-3 pt-8 border-b border-surface-container pb-4 sticky top-0 bg-background/90 backdrop-blur-md z-10">
        <Icon name="podcasts" size="xl" color="primary" />
        <div>
          <Typography variant="headline" className="font-bold">Podcast Studio</Typography>
        </div>
      </div>

      {/* Bottom Input Bar Section */}
      <div className="absolute bottom-0 left-0 w-full px-4 pb-8 pt-4 bg-gradient-to-t from-background via-background to-transparent z-50">
        {error && <div className="max-w-4xl mx-auto mb-2"><ErrorAlert message={error} /></div>}
        <div className="max-w-4xl mx-auto flex items-end gap-2 bg-surface-container-high rounded-full p-2 shadow-2xl border border-outline-variant/20 backdrop-blur-xl">

          <textarea 
            className="flex-1 bg-transparent border-none focus:ring-0 text-on-surface text-body-md py-2 resize-none placeholder:text-text-secondary max-h-32 min-h-[40px] outline-none" 
            placeholder="What should the podcast be about?" 
            rows={1}
            value={prompt}
            onChange={(e) => {
              setPrompt(e.target.value);
              if (error) setError(null);
            }}
            onKeyDown={(e) => {
              if (e.key === 'Enter' && !e.shiftKey) {
                e.preventDefault();
                handleGenerate();
              }
            }}
          />
          
          {prompt.trim() ? (
             <button onClick={handleGenerate} disabled={loading} className="w-10 h-10 flex items-center justify-center bg-primary text-on-primary rounded-full transition-all shadow-lg shadow-primary/20 flex-shrink-0 disabled:opacity-50">
               <Icon name={loading ? "hourglass_empty" : "send"} />
             </button>
          ) : (
            <div className="flex items-center flex-shrink-0">
              <button 
                onClick={toggleRecording} 
                disabled={loading}
                className={`w-10 h-10 flex items-center justify-center rounded-full transition-colors disabled:opacity-50 ${isRecording ? 'bg-red-500 text-white animate-pulse' : 'text-text-secondary hover:bg-surface-container-highest'}`}
              >
                <Icon name="mic" />
              </button>
            </div>
          )}
        </div>
      </div>

      {/* Streaming Thoughts */}
      {loading && thinkingText && (
        <div className="p-4 bg-surface-container rounded-xl border border-primary/20 flex flex-col gap-2">
          <div className="flex items-center gap-2">
            <div className="w-4 h-4 rounded-full border-2 border-primary border-t-transparent animate-spin" />
            <Typography variant="label-sm" color="primary" className="font-bold">Analyzing & Generating...</Typography>
          </div>
          <Typography variant="body-sm" color="secondary" className="italic whitespace-pre-wrap">
            {thinkingText}
          </Typography>
        </div>
      )}

      {/* Output Podcast Card */}
      {podcastResult && (
        <div className="p-5 bg-surface-container border border-primary/40 rounded-2xl shadow-2xl flex flex-col gap-4 text-white">
          <div className="flex items-center gap-4">
            <div className="relative w-24 h-24 rounded-xl overflow-hidden shadow-md flex-shrink-0 group">
              {podcastResult.coverUrl ? (
                <img
                  src={podcastResult.coverUrl}
                  alt="Podcast Cover"
                  loading="lazy"
                  className="w-full h-full object-cover"
                />
              ) : (
                <div className="w-full h-full bg-surface flex items-center justify-center">
                  <Icon name="podcasts" size="lg" />
                </div>
              )}
              {/* Overlay Actions */}
              <div className="absolute inset-0 bg-black/40 opacity-0 group-hover:opacity-100 transition-opacity flex flex-col justify-end p-1">
                <div className="flex justify-between items-center">
                  <button onClick={() => handleAction('like', podcastResult.id || prompt)} className="p-1 hover:text-primary transition-colors text-white" title="Like">
                    <Icon name="favorite_border" size="sm" />
                  </button>
                  <button 
                      onClick={(e) => {
                        e.stopPropagation();
                        handleAction('share', podcastResult.id || prompt);
                      }} 
                      className="p-2 hover:bg-white/10 rounded-full transition-colors text-white"
                      title="Share"
                    >
                      <Icon name="share" size="sm" />
                    </button>
                </div>
              </div>
            </div>
            <div className="flex-1 overflow-hidden">
              <Typography variant="title-md" className="font-bold truncate">{podcastResult.title}</Typography>
              <Typography variant="label-sm" color="secondary">Voice: {podcastResult.voice} • Duration: {podcastResult.duration}</Typography>
            </div>
          </div>

          <div className="bg-surface/80 p-3.5 rounded-xl border border-outline/20">
            <Typography variant="label-sm" color="primary" className="font-bold mb-1">EPISODE TRANSCRIPT</Typography>
            <p className="text-xs text-text-primary italic leading-relaxed font-serif">
              "{podcastResult.script}"
            </p>
          </div>

          <div className="flex items-center justify-between pt-1">
            <span className="text-[10px] text-text-secondary font-semibold">GOOGLE CLOUD</span>
            <button
              onClick={() => {
                if (typeof navigator !== 'undefined' && navigator.vibrate) {
                  navigator.vibrate([50, 50, 50]);
                }
                setCurrentTrack({
                  id: podcastResult.id || Date.now().toString(),
                  title: podcastResult.title,
                  artist: `Voice: ${podcastResult.voice || 'AOEDE'}`,
                  albumArtUrl: podcastResult.coverUrl,
                });
                setIsPlaying(true);
              }}
              className="px-4 py-2 bg-primary text-black rounded-full text-xs font-bold flex items-center gap-1.5 hover:brightness-110 active:scale-95 transition-all shadow"
              title="Listen"
            >
              <Icon name="play_arrow" size="sm" />
            </button>
          </div>
        </div>
      )}
    </div>
  );
};
